import type { AgentColorTheme } from './types';

export const AGENT_THEMES: Record<string, AgentColorTheme> = {
  withdraw_pf: {
    name: 'withdraw_pf',
    primary: 'blue-600',
    primaryRgb: '59,130,246',
    gradient: 'from-blue-500 to-indigo-600',
    ring: 'ring-blue-200',
    chatBubble: 'bg-blue-50 border-blue-200/60',
    textPrimary: 'text-blue-600',
    textDark: 'text-blue-900',
    bgLight: 'bg-blue-50',
    borderLight: 'border-blue-200/80',
    icon: '💰',
    label: 'Withdraw PF Agent',
  },
  kyc_mismatch: {
    name: 'kyc_mismatch',
    primary: 'amber-600',
    primaryRgb: '217,119,6',
    gradient: 'from-amber-500 to-orange-600',
    ring: 'ring-amber-200',
    chatBubble: 'bg-amber-50 border-amber-200/60',
    textPrimary: 'text-amber-600',
    textDark: 'text-amber-900',
    bgLight: 'bg-amber-50',
    borderLight: 'border-amber-200/80',
    icon: '📋',
    label: 'KYC Fix Agent',
  },
  aadhaar_fix: {
    name: 'aadhaar_fix',
    primary: 'rose-600',
    primaryRgb: '225,29,72',
    gradient: 'from-rose-500 to-pink-600',
    ring: 'ring-rose-200',
    chatBubble: 'bg-rose-50 border-rose-200/60',
    textPrimary: 'text-rose-600',
    textDark: 'text-rose-900',
    bgLight: 'bg-rose-50',
    borderLight: 'border-rose-200/80',
    icon: '🪪',
    label: 'Aadhaar Fix Agent',
  },
  transfer_pf: {
    name: 'transfer_pf',
    primary: 'violet-600',
    primaryRgb: '124,58,237',
    gradient: 'from-violet-500 to-purple-600',
    ring: 'ring-violet-200',
    chatBubble: 'bg-violet-50 border-violet-200/60',
    textPrimary: 'text-violet-600',
    textDark: 'text-violet-900',
    bgLight: 'bg-violet-50',
    borderLight: 'border-violet-200/80',
    icon: '🔄',
    label: 'Transfer PF Agent',
  },
  mark_exit: {
    name: 'mark_exit',
    primary: 'teal-600',
    primaryRgb: '13,148,136',
    gradient: 'from-teal-500 to-emerald-600',
    ring: 'ring-teal-200',
    chatBubble: 'bg-teal-50 border-teal-200/60',
    textPrimary: 'text-teal-600',
    textDark: 'text-teal-900',
    bgLight: 'bg-teal-50',
    borderLight: 'border-teal-200/80',
    icon: '🚪',
    label: 'Mark Exit Agent',
  },
  life_certificate: {
    name: 'life_certificate',
    primary: 'rose-600',
    primaryRgb: '225,29,72',
    gradient: 'from-rose-500 to-pink-600',
    ring: 'ring-rose-200',
    chatBubble: 'bg-rose-50 border-rose-200/60',
    textPrimary: 'text-rose-600',
    textDark: 'text-rose-900',
    bgLight: 'bg-rose-50',
    borderLight: 'border-rose-200/80',
    icon: '📸',
    label: 'Life Certificate Agent',
  },
  merge_accounts: {
    name: 'merge_accounts',
    primary: 'orange-600',
    primaryRgb: '234,88,12',
    gradient: 'from-orange-500 to-red-600',
    ring: 'ring-orange-200',
    chatBubble: 'bg-orange-50 border-orange-200/60',
    textPrimary: 'text-orange-600',
    textDark: 'text-orange-900',
    bgLight: 'bg-orange-50',
    borderLight: 'border-orange-200/80',
    icon: '🔗',
    label: 'Merge Accounts Agent',
  },
  grievance: {
    name: 'grievance',
    primary: 'slate-600',
    primaryRgb: '75,85,99',
    gradient: 'from-slate-500 to-slate-700',
    ring: 'ring-slate-200',
    chatBubble: 'bg-slate-50 border-slate-200/60',
    textPrimary: 'text-slate-600',
    textDark: 'text-slate-900',
    bgLight: 'bg-slate-50',
    borderLight: 'border-slate-200/80',
    icon: '⚖️',
    label: 'Grievance Agent',
  },
  general_inquiry: {
    name: 'general_inquiry',
    primary: 'blue-500',
    primaryRgb: '59,130,246',
    gradient: 'from-blue-400 to-blue-600',
    ring: 'ring-blue-100',
    chatBubble: 'bg-blue-50 border-blue-100/60',
    textPrimary: 'text-blue-500',
    textDark: 'text-blue-800',
    bgLight: 'bg-blue-50',
    borderLight: 'border-blue-100/80',
    icon: '❓',
    label: 'General Inquiry Agent',
  },
};

export const DEFAULT_THEME = AGENT_THEMES.general_inquiry;

export function getTheme(flowType: string): AgentColorTheme {
  return AGENT_THEMES[flowType] || DEFAULT_THEME;
}
